// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.CMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.CMS.Mappings.Configurations
{
    public partial class AccessPermissionConfiguration : IEntityTypeConfiguration<AccessPermission>
    {
        public void Configure(EntityTypeBuilder<AccessPermission> entity)
        {
            entity.ToTable("AccessPermission", "dam");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.HasOne(d => d.Item)
                .WithMany(p => p.AccessPermission)
                .HasForeignKey(d => d.ItemId)
                .HasConstraintName("FK_AccessPermission_Item");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<AccessPermission> entity);
    }
}
