// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.CMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.CMS.Mappings.Configurations
{
    public partial class ContentCategoryMappingConfiguration : IEntityTypeConfiguration<ContentCategoryMapping>
    {
        public void Configure(EntityTypeBuilder<ContentCategoryMapping> entity)
        {
            entity.ToTable("Content_Category_Mapping", "dam");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Category)
                .WithMany(p => p.ContentCategoryMapping)
                .HasForeignKey(d => d.CategoryId)
                .HasConstraintName("FK_Content_Category_Mapping_Category_CategoryId");

            entity.HasOne(d => d.Content)
                .WithMany(p => p.ContentCategoryMapping)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK_Content_Category_Mapping_Content_ContentId");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContentCategoryMapping> entity);
    }
}
