// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.CMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.CMS.Mappings.Configurations
{
    public partial class ContentGroupCategoryMappingConfiguration : IEntityTypeConfiguration<ContentGroupCategoryMapping>
    {
        public void Configure(EntityTypeBuilder<ContentGroupCategoryMapping> entity)
        {
            entity.ToTable("Content_GroupCategory_Mapping", "dam");

            entity.HasIndex(e => e.ContentId, "index_Content_GroupCategory_Mapping_ProductId");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.GroupCategory)
                .WithMany(p => p.ContentGroupCategoryMapping)
                .HasForeignKey(d => d.GroupCategoryId)
                .HasConstraintName("FK_Content_GroupCategory_Mapping_Group_Category");

            entity.HasOne(d => d.Content)
                .WithMany(p => p.ContentGroupCategoryMapping)
                .HasForeignKey(d => d.ContentId)
                .HasConstraintName("FK_Content_GroupCategory_Mapping_Content");
            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContentGroupCategoryMapping> entity);
    }
}
