// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.CMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.CMS.Mappings.Configurations
{
    public partial class ItemConfiguration : IEntityTypeConfiguration<Item>
    {
        public void Configure(EntityTypeBuilder<Item> entity)
        {
            entity.ToTable("Item", "dam");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.Cdn).HasMaxLength(255);

            entity.Property(e => e.Content).HasColumnType("ntext");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");

            entity.Property(e => e.Description).HasMaxLength(500);

            entity.Property(e => e.LocalPath).HasMaxLength(255); 
            entity.Property(e => e.VirtualPath).HasMaxLength(255);

            entity.Property(e => e.MimeType).HasMaxLength(50);

            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255);

            entity.Property(e => e.Product)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Tenant)
                .HasMaxLength(50)
                .IsUnicode(false);

            entity.Property(e => e.Title).HasMaxLength(255);

            entity.Property(e => e.UpdatedDate).HasColumnType("datetime");

            entity.Property(e => e.Workspace).HasMaxLength(255);

            OnConfigurePartial(entity);

            entity.HasOne(d => d.ParentItem)
                .WithMany(p => p.InverseParentItem)
                .HasForeignKey(d => d.ParentId)
                .HasConstraintName("FK_Item_Item");
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Item> entity);
    }
}
