// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.CMS.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace VFi.Infra.CMS.Mappings.Configurations
{
    public partial class OpenActivityConfiguration : IEntityTypeConfiguration<OpenActivity>
    {
        public void Configure(EntityTypeBuilder<OpenActivity> entity)
        {
            entity.ToTable("OpenActivity", "dam");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.Property(e => e.OpenDate).HasColumnType("datetime");

            entity.HasOne(d => d.Item)
                .WithMany(p => p.OpenActivity)
                .HasForeignKey(d => d.ItemId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OpenActivity_Item");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<OpenActivity> entity);
    }
}
