// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using VFi.Domain.CMS.Models;
using VFi.NetDevPack.Domain;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace VFi.Domain.CMS.Models
{
    public interface IDAMContextProcedures
    {
        Task<int> SP_COPY_CONTENTAsync(Guid? ContentId, string new_ContentCode, string new_ContentName, int? new_Status, Guid? createdBy, string? createdByName, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GET_TOP_NEW_CONTENT>> SP_GET_TOP_NEW_CONTENTAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GET_TOP_CATEGORY>> SP_GET_TOP_CATEGORYAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<SP_GET_CONTENT_BY_CONTENTTYPE>> SP_GET_CONTENT_BY_CONTENTTYPEAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
