// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.CMS.Models
{
    public partial class Activity : Entity, IAggregateRoot
    { 
        public Guid ItemId { get; set; }
        public Guid AccountId { get; set; }
        public DateTime CreatedDate { get; set; }
        public string Body { get; set; }

        public virtual Item Item { get; set; }
    }
}