// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace VFi.Domain.CMS.Models
{
    public partial class Content : Entity, IAggregateRoot
    {
        public Content()
        {
            ContentCategoryMapping = new HashSet<ContentCategoryMapping>();
            ContentGroupCategoryMapping = new HashSet<ContentGroupCategoryMapping>();
        }

        public Guid? ContentTypeId { get; set; }
        public string ContentType { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string LinkInfo { get; set; }
        public string ShortDescription { get; set; }
        public string FullDescription { get; set; }
        public Guid? CategoryRootId { get; set; }
        public string CategoryRoot { get; set; }
        public string IdGroupCategories { get; set; }
        public string GroupCategories { get; set; }
        public string Categories { get; set; }
        public string IdCategories { get; set; }
        public string Image { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public bool? Deleted { get; set; }
        public DateTime? DeletedDate { get; set; }
        public int? Status { get; set; }
        public Guid? CreatedBy { get; set; }
        public string CreatedByName { get; set; }
        public Guid? UpdatedBy { get; set; }
        public string UpdatedByName { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public string Tags { get; set; }
        public string Slug { get; set; } 
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int IdNumber { get; set; }

        public DateTime? PublishDate { get; set; }
        public string ApproveByName { get; set; }
        public Guid? ApproveBy { get; set; }
        public int? DisplayOrder { get; set; }
        public int? DisplayTop { get; set; }
        public int? DisplayTop1 { get; set; }
        public int? DisplayTop2 { get; set; }
        public string LoopQuery { get; set; }
        public string LoopLink { get; set; }
        public string LoopTitle { get; set; }
        public virtual CategoryRoot CategoryRootNavigation { get; set; }
        public virtual ICollection<ContentCategoryMapping> ContentCategoryMapping { get; set; }
        public virtual ICollection<ContentGroupCategoryMapping> ContentGroupCategoryMapping { get; set; }
        public virtual ContentType ContentTypes { get; set; }

    }
}