// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.CMS.Models
{
    public partial class ContentCategoryMapping : Entity, IAggregateRoot
    { 
        public Guid CategoryId { get; set; }
        public Guid ContentId { get; set; }
        public int DisplayOrder { get; set; }
        public Guid? GroupCategoryId { get; set; }

        public virtual Category Category { get; set; }
        public virtual Content Content { get; set; }
    }
}