// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.CMS.Models
{
    public partial class Item : Entity, IAggregateRoot
    {
        public Item()
        {
            AccessPermission = new HashSet<AccessPermission>();
            Activity = new HashSet<Activity>();
            OpenActivity = new HashSet<OpenActivity>();
            InverseParentItem = new HashSet<Item>();

    }

    public string Name { get; set; }
    public string Title { get; set; }
    public string Description { get; set; }
    public int? Size { get; set; }
    public bool IsFile { get; set; }
    public Guid? ParentId { get; set; }
    public string MimeType { get; set; }
    public bool? HasChild { get; set; }
    public string VirtualPath { get; set; }
    public string LocalPath { get; set; }
    public string Cdn { get; set; }
    public Guid? CreatedBy { get; set; }
    public DateTime? CreatedDate { get; set; }
    public Guid? UpdatedBy { get; set; }
    public DateTime? UpdatedDate { get; set; }
    public string Product { get; set; }
    public int? Status { get; set; }
    public string? Workspace { get; set; }
    public string Content { get; set; }
    public string Tenant { get; set; }
    public string? CreatedByName { get; set; }
    public string? UpdatedByName { get; set; }
    public bool? Deleted { get; set; }
    public DateTime? DeletedDate { get; set; }
    public DateTime? LastOpenDate { get; set; }
    public virtual Item ParentItem { get; set; }
    public virtual ICollection<Item> InverseParentItem { get; set; }
    public virtual ICollection<AccessPermission> AccessPermission { get; set; }
    public virtual ICollection<Activity> Activity { get; set; }
    public virtual ICollection<OpenActivity> OpenActivity { get; set; }
}
}