// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using VFi.NetDevPack.Domain;
using System;
using System.Collections.Generic;

namespace VFi.Domain.CMS.Models
{
    public partial class WebLink : Entity, IAggregateRoot
    {
        public WebLink()
        {
            InverseParentWebLink = new HashSet<WebLink>();
        }

        public string Code { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Url { get; set; }
        public Guid? ParentWebLinkId { get; set; }
        public string Keywords { get; set; }
        public int Status { get; set; }
        public int DisplayOrder { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public Guid? CreatedBy { get; set; }
        public Guid? UpdatedBy { get; set; }
        public Guid? GroupWebLinkId { get; set; }
        public string ParentIds { get; set; }
        public int? Level { get; set; }
        public string GroupWebLinkCode { get; set; }
        public string GroupWebLinkName { get; set; }
        public string CreatedByName { get; set; }
        public string UpdatedByName { get; set; }

        public virtual GroupWebLink GroupWebLink { get; set; }
        public virtual WebLink ParentWebLink { get; set; }
        public virtual ICollection<WebLink> InverseParentWebLink { get; set; }
    }
}